{% set name = "powergenome" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PowerGenome-{{ version }}.tar.gz
  sha256: 304fc637c860fb0a9ca4dd34f72169aa6d18a60d3f1e5d6fa63c0e9e85730f04

build:
  entry_points:
    - run_powergenome_multiple = powergenome.run_powergenome_multiple_outputs_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=66,<68
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - catalystcoop.pudl >=0.6.0,<=2022.11.30
    - beautifulsoup4 >=4.8.13
    - statsmodels >=0.12.2
    - python-dotenv
    - flatten-dict
    - ruamel.yaml
    - pyyaml
    - frozendict
    - openpyxl >=3.0
    - geopandas >=0.11

test:
  imports:
    - powergenome
  commands:
    - pip check
    - run_powergenome_multiple --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PowerGenome/PowerGenome
  summary: Create power system inputs for capacity expansion models
  dev_url: https://github.com/PowerGenome/PowerGenome
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - gschivley
